{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-back-svc
spec:
  selector:
    app: {{ .Release.Name }}-back
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
{{- end }}

