apiVersion: v1
kind: ConfigMap
metadata:
  name: back-env
data:
    DB_HOST         : db
    DB_PORT         : "5432"
    DB_USERNAME     : postgres
    DB_DATABASE     : devops_lessons
    PORT            : "7000"
    HOST            : "0.0.0.0"
    NODE_ENV        : development
    APP_NAME        : Lessons
    APP_DESCRIPTION : Devops lessons REST API
