{{- if .Values.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.pvc.claimName }}
spec:
  accessModes:
    {{- range .Values.db.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.pvc.size }}
  storageClassName: {{ .Values.db.storageClass.name }}
{{- end }}

