{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: {{ .Values.db.containerPort }}
{{- end }}

