{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front-svc
spec:
  selector:
    app: {{ .Release.Name }}-front
  ports:
   - port: {{ .Values.frontend.servicePort }}
     targetPort: {{ .Values.frontend.containerPort }}
{{- end }}

