apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: my-github-runner
  namespace: github-actions 
spec:
  ephemeral: false
  repository: EdgarHarutyunyan2025/docker
  labels: ["linux", "x64"]
  env:
    - name: ACTIONS_RUNNER_INPUT_GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-actions-runner-token
          key: github_token
  resources:
    requests:
      memory: "512Mi"  
      cpu: "500m"     
    limits:
      memory: "2Gi" 
      cpu: "1" 
